### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by johnxpres** [skvortsovden/saymytext#1]
(venv) PS C:\Users\PC\PycharmProjects\pythonProject1> pip install saymytext
Collecting saymytext
  Using cached saymytext-1.0-py3-none-any.whl (2.7 kB)
Collecting PyAudio==0.2.11
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pydub==0.25.1 in c:\users\pc\pycharmprojects\pythonproject1\venv\lib\site-packages (from saymytext) (0.25.1)
Collecting gTTS==2.2.3
  Using cached gTTS-2.2.3-py3-none-any.whl (25 kB)
Requirement already satisfied: click in c:\users\pc\pycharmprojects\pythonproject1\venv\lib\site-packages (from gTTS==2.2.3->saymytext) (8.1.3)
Requirement already satisfied: six in c:\users\pc\pycharmprojects\pythonproject1\venv\lib\site-packages (from gTTS==2.2.3->saymytext) (1.16.0)
Requirement already satisfied: requests in c:\users\pc\pycharmprojects\pythonproject1\venv\lib\site-packages (from gTTS==2.2.3->saymytext) (2.28.1)
Requirement already satisfied: colorama in c:\users\pc\pycharmprojects\pythonproject1\venv\lib\site-packages (from click->gTTS==2.2.3->saymytext) (0.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pc\pycharmprojects\pythonproject1\venv\lib\site-packages (from requests->gTTS==2.2.3->saymytext) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\pc\pycharmprojects\pythonproject1\venv\lib\site-packages (from requests->gTTS==2.2.3->saymytext) (1.26.11)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\pc\pycharmprojects\pythonproject1\venv\lib\site-packages (from requests->gTTS==2.2.3->saymytext) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pc\pycharmprojects\pythonproject1\venv\lib\site-packages (from requests->gTTS==2.2.3->saymytext) (2022.6.15)
Building wheels for collected packages: PyAudio
  Building wheel for PyAudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\PC\PycharmProjects\pythonProject1\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Temp
\\pip-install-aen652tc\\pyaudio_7f5f51e46f0144b99519429fc984a75e\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-aen652tc\\pyaudio_7f5f51e46f0144b9951942
9fc984a75e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\PC\AppData\Local\Temp\pip-wheel-y8o4p2p8'
       cwd: C:\Users\PC\AppData\Local\Temp\pip-install-aen652tc\pyaudio_7f5f51e46f0144b99519429fc984a75e\
  Complete output (54 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.10
  copying src\pyaudio.py -> build\lib.win-amd64-3.10
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\PC\AppData\Local\Temp\pip-install-aen652tc\pyaudio_7f5f51e46f0144b99519429fc984a75e\setup.py", line 106, in <module>
      setup(name='PyAudio',
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
      _build_ext.build_extension(self, ext)
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 327, in compile
      self.initialize()
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  setuptools._distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for PyAudio
  Running setup.py clean for PyAudio
Failed to build PyAudio
Installing collected packages: PyAudio, gTTS, saymytext
  Attempting uninstall: PyAudio
    Found existing installation: PyAudio 0.2.12
    Uninstalling PyAudio-0.2.12:
      Successfully uninstalled PyAudio-0.2.12
    Running setup.py install for PyAudio ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\PC\PycharmProjects\pythonProject1\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Te
mp\\pip-install-aen652tc\\pyaudio_7f5f51e46f0144b99519429fc984a75e\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-aen652tc\\pyaudio_7f5f51e46f0144b99519
429fc984a75e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f
.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PC\AppData\Local\Temp\pip-record-clpljctu\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\PC\PycharmProjects\pythonProject1\venv\include\site\python3.10\PyAudio'
         cwd: C:\Users\PC\AppData\Local\Temp\pip-install-aen652tc\pyaudio_7f5f51e46f0144b99519429fc984a75e\
    Complete output (10 lines):
    running install
    C:\Users\PC\PycharmProjects\pythonProject1\venv\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    copying src\pyaudio.py -> build\lib.win-amd64-3.10
    running build_ext
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
  Rolling back uninstall of PyAudio
  Moving to c:\users\pc\pycharmprojects\pythonproject1\venv\lib\site-packages\__pycache__\pyaudio.cpython-310.pyc
   from C:\Users\PC\AppData\Local\Temp\pip-uninstall-cieqmlq0\pyaudio.cpython-310.pyc
  Moving to c:\users\pc\pycharmprojects\pythonproject1\venv\lib\site-packages\_portaudio.cp310-win_amd64.pyd
   from C:\Users\PC\AppData\Local\Temp\pip-uninstall-f_hz_6dq\_portaudio.cp310-win_amd64.pyd
  Moving to c:\users\pc\pycharmprojects\pythonproject1\venv\lib\site-packages\pyaudio-0.2.12.dist-info\
   from C:\Users\PC\PycharmProjects\pythonProject1\venv\Lib\site-packages\~yaudio-0.2.12.dist-info
  Moving to c:\users\pc\pycharmprojects\pythonproject1\venv\lib\site-packages\pyaudio.py
   from C:\Users\PC\AppData\Local\Temp\pip-uninstall-f_hz_6dq\pyaudio.py
ERROR: Command errored out with exit status 1: 'C:\Users\PC\PycharmProjects\pythonProject1\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'
C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-aen652tc\\pyaudio_7f5f51e46f0144b99519429fc984a75e\\setup.py'"'"'; __file__='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-aen65
2tc\\pyaudio_7f5f51e46f0144b99519429fc984a75e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools imp
ort setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PC\AppData\Local\Temp
\pip-record-clpljctu\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\PC\PycharmProjects\pythonProject1\venv\include\site\python3.10\PyAudio' Check the logs for full command output.
WARNING: You are using pip version 21.3.1; however, version 22.2.2 is available.
You should consider upgrading via the 'C:\Users\PC\PycharmProjects\pythonProject1\venv\Scripts\python.exe -m pip install --upgrade pip' command.
(venv) PS C:\Users\PC\PycharmProjects\pythonProject1>

**Comment by johnxpres** [comment]
Please tell me what is the problem

**Comment by sdenysv** [comment]
Hi.
The error is: 
Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools.

You could try to update build tools on your windows machine.
Go to https://visualstudio.microsoft.com/visual-cpp-build-tools/ download
and update.
